/*
 * Copyright (C)  2005. Marvell International Ltd
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef __AUDIO_PROFILE_H__
#define __AUDIO_PROFILE_H__

#include <system/audio.h>
#include "acm_api.h"

// profile flags
#define PROFILE_BT_WB 0x00000001
#define PROFILE_BT_NREC_OFF 0x00000002
#define PROFILE_BT_STEREO 0x00000004
#define PROFILE_EXTRA_VOL 0x00000008
#define PROFILE_LOOP 0x00000010
#define PROFILE_LOOP_ENH_OFF 0x00000020
#define PROFILE_TTY 0x00000040
#define PROFILE_HCO 0x00000080
#define PROFILE_VCO 0x00000100
#define PROFILE_DUAL_MIC 0x00000200
#define PROFILE_LTE 0x00000400

// Audio profile operation methods
#define PROFILE_ENABLE 0x00000001
#define PROFILE_DISABLE 0x00000002

// definition of Audio Profile
typedef enum {
  VC_HANDSET = 0,
  VC_HANDSFREE,
  VC_HEADSET,
  VC_HEADPHONE,
  VC_SPEAKERPHONE,
  VC_BT_NB,
  VC_BT_NREC_OFF_NB,
  VC_STEREO_BT_NB,
  VC_BT_WB,
  VC_BT_NREC_OFF_WB,
  VC_STEREO_BT_WB,
  VC_HANDSET_EXTRAVOL_ON,
  VC_HANDSFREE_EXTRAVOL_ON,
  VC_HANDSET_DUALMIC,
  VC_HEADSET_DUALMIC,
  VC_HANDSFREE_DUALMIC,

  // LOOP means LOOP with enhancement
  VC_HANDSET_LOOP,
  VC_HANDSFREE_LOOP,
  VC_HEADSET_LOOP,
  VC_BT_NB_LOOP,
  VC_BT_WB_LOOP,

  // LOOP_ENH_OFF means LOOP without enhancement
  VC_HANDSET_LOOP_ENH_OFF,
  VC_HANDSFREE_LOOP_ENH_OFF,
  VC_HEADSET_LOOP_ENH_OFF,
  VC_BT_NB_LOOP_ENH_OFF,
  VC_BT_WB_LOOP_ENH_OFF,

  VC_TTY,
  VC_TTY_HCO_EARPIECE,
  VC_TTY_HCO_SPEAKER,
  VC_TTY_VCO_EARPIECE,
  VC_TTY_VCO_SPEAKER,
  VC_TTY_VCO_EARPIECE_DUALMIC,
  VC_TTY_VCO_SPEAKER_DUALMIC,

  VOLTE_HANDSET,
  VOLTE_HANDSFREE,
  VOLTE_HEADSET,
  VOLTE_HEADPHONE,
  VOLTE_SPEAKERPHONE,
  VOLTE_BT_NB,
  VOLTE_BT_NREC_OFF_NB,
  VOLTE_STEREO_BT_NB,
  VOLTE_BT_WB,
  VOLTE_BT_NREC_OFF_WB,
  VOLTE_STEREO_BT_WB,
  VOLTE_HANDSET_EXTRAVOL_ON,
  VOLTE_HANDSFREE_EXTRAVOL_ON,
  VOLTE_HANDSET_DUALMIC,
  VOLTE_HEADSET_DUALMIC,
  VOLTE_HANDSFREE_DUALMIC,

  VOIP_HANDSET = 0x50,
  VOIP_HANDSFREE,
  VOIP_HEADSET,
  VOIP_HEADPHONE,
  VOIP_SPEAKERPHONE,
  VOIP_BT_NB,
  VOIP_BT_NREC_OFF_NB,
  VOIP_STEREO_BT_NB,
  VOIP_BT_WB,
  VOIP_BT_NREC_OFF_WB,
  VOIP_STEREO_BT_WB,
  VOIP_HANDSET_EXTRAVOL_ON,
  VOIP_HANDSFREE_EXTRAVOL_ON,
  VOIP_HANDSET_DUALMIC,
  VOIP_HEADSET_DUALMIC,
  VOIP_HANDSFREE_DUALMIC,
  VOIP_HANDSET_LOOP,
  VOIP_HANDSFREE_LOOP,
  VOIP_HEADSET_LOOP,
  VOIP_BT_NB_LOOP,
  VOIP_BT_WB_LOOP,

  HIFI_SPEAKER = 0x80,
  HIFI_HEADSET,
  HIFI_MIC,
  HIFI_DUAL_MIC,

  VT_HANDSET = 0xA0,
  VT_HANDSFREE,
  VT_HEADSET,
  VT_HEADPHONE,
  VT_SPEAKERPHONE,
  VT_BT_NB,
  VT_BT_NREC_OFF_NB,
  VT_STEREO_BT_NB,
  VT_BT_WB,
  VT_BT_NREC_OFF_WB,
  VT_STEREO_BT_WB,
  VT_HANDSET_EXTRAVOL_ON,
  VT_HANDSFREE_EXTRAVOL_ON,
  VT_HANDSET_DUALMIC,
  VT_HEADSET_DUALMIC,
  VT_HANDSFREE_DUALMIC,
  VT_HANDSET_LOOP,
  VT_HANDSFREE_LOOP,
  VT_HEADSET_LOOP,
  VT_BT_NB_LOOP,
  VT_BT_WB_LOOP,

  AUDIO_PROFILE_ID_ENUM_32_BIT = 0x7FFFFFFF  // 32bit enum compiling enforcement
} AUDIO_PROFILE_ID;

// define profile table
#define PROFILE_NAME(e) #e
#define MAX_NUM_PROFILE (sizeof(gProfile) / sizeof(gProfile[0]))
static const struct {
  audio_mode_t v_mode;
  uint32_t out_device;
  uint32_t in_device;
  uint32_t flag;
  char *profile;
} gProfile[] = {
    // Voice Call Profile
    {AUDIO_MODE_IN_CALL, AUDIO_DEVICE_OUT_EARPIECE, 0, 0,
     PROFILE_NAME(VC_HANDSET)},
    {AUDIO_MODE_IN_CALL, AUDIO_DEVICE_OUT_SPEAKER, 0, 0,
     PROFILE_NAME(VC_HANDSFREE)},
    {AUDIO_MODE_IN_CALL, AUDIO_DEVICE_OUT_WIRED_HEADSET, 0, 0,
     PROFILE_NAME(VC_HEADSET)},
    {AUDIO_MODE_IN_CALL, AUDIO_DEVICE_OUT_WIRED_HEADPHONE, 0, 0,
     PROFILE_NAME(VC_HEADPHONE)},
    {AUDIO_MODE_IN_CALL,
     AUDIO_DEVICE_OUT_SPEAKER | AUDIO_DEVICE_OUT_WIRED_HEADPHONE, 0, 0,
     PROFILE_NAME(VC_SPEAKERPHONE)},
    {AUDIO_MODE_IN_CALL, AUDIO_DEVICE_OUT_BLUETOOTH_SCO_HEADSET, 0, 0,
     PROFILE_NAME(VC_BT_NB)},
    {AUDIO_MODE_IN_CALL, AUDIO_DEVICE_OUT_BLUETOOTH_SCO_HEADSET, 0,
     PROFILE_BT_NREC_OFF, PROFILE_NAME(VC_BT_NREC_OFF_NB)},
    {AUDIO_MODE_IN_CALL, AUDIO_DEVICE_OUT_BLUETOOTH_SCO_HEADSET, 0,
     PROFILE_BT_STEREO, PROFILE_NAME(VC_STEREO_BT_NB)},
    {AUDIO_MODE_IN_CALL, AUDIO_DEVICE_OUT_BLUETOOTH_SCO_HEADSET, 0,
     PROFILE_BT_WB, PROFILE_NAME(VC_BT_WB)},
    {AUDIO_MODE_IN_CALL, AUDIO_DEVICE_OUT_BLUETOOTH_SCO_HEADSET, 0,
     PROFILE_BT_NREC_OFF | PROFILE_BT_WB, PROFILE_NAME(VC_BT_NREC_OFF_WB)},
    {AUDIO_MODE_IN_CALL, AUDIO_DEVICE_OUT_BLUETOOTH_SCO_HEADSET, 0,
     PROFILE_BT_STEREO | PROFILE_BT_WB, PROFILE_NAME(VC_STEREO_BT_WB)},
    {AUDIO_MODE_IN_CALL, AUDIO_DEVICE_OUT_EARPIECE, 0, PROFILE_EXTRA_VOL,
     PROFILE_NAME(VC_HANDSET_EXTRAVOL_ON)},
    {AUDIO_MODE_IN_CALL, AUDIO_DEVICE_OUT_SPEAKER, 0, PROFILE_EXTRA_VOL,
     PROFILE_NAME(VC_HANDSFREE_EXTRAVOL_ON)},
    {AUDIO_MODE_IN_CALL, AUDIO_DEVICE_OUT_EARPIECE, 0, PROFILE_DUAL_MIC,
     PROFILE_NAME(VC_HANDSET_DUALMIC)},
    {AUDIO_MODE_IN_CALL, AUDIO_DEVICE_OUT_EARPIECE, 0, PROFILE_DUAL_MIC,
     PROFILE_NAME(VC_HEADSET_DUALMIC)},
    {AUDIO_MODE_IN_CALL, AUDIO_DEVICE_OUT_SPEAKER, 0, PROFILE_DUAL_MIC,
     PROFILE_NAME(VC_HANDSFREE_DUALMIC)},

    {AUDIO_MODE_IN_CALL, AUDIO_DEVICE_OUT_EARPIECE, 0, PROFILE_LOOP,
     PROFILE_NAME(VC_HANDSET_LOOP)},
    {AUDIO_MODE_IN_CALL, AUDIO_DEVICE_OUT_SPEAKER, 0, PROFILE_LOOP,
     PROFILE_NAME(VC_HANDSFREE_LOOP)},
    {AUDIO_MODE_IN_CALL, AUDIO_DEVICE_OUT_WIRED_HEADSET, 0, PROFILE_LOOP,
     PROFILE_NAME(VC_HEADSET_LOOP)},
    {AUDIO_MODE_IN_CALL, AUDIO_DEVICE_OUT_BLUETOOTH_SCO_HEADSET, 0,
     PROFILE_LOOP, PROFILE_NAME(VC_BT_NB_LOOP)},
    {AUDIO_MODE_IN_CALL, AUDIO_DEVICE_OUT_BLUETOOTH_SCO_HEADSET, 0,
     PROFILE_LOOP, PROFILE_NAME(VC_BT_WB_LOOP)},

    {AUDIO_MODE_IN_CALL, AUDIO_DEVICE_OUT_SPEAKER, 0, PROFILE_LOOP_ENH_OFF,
     PROFILE_NAME(VC_HANDSET_LOOP_ENH_OFF)},
    {AUDIO_MODE_IN_CALL, AUDIO_DEVICE_OUT_EARPIECE, 0, PROFILE_LOOP_ENH_OFF,
     PROFILE_NAME(VC_HANDSFREE_LOOP_ENH_OFF)},
    {AUDIO_MODE_IN_CALL, AUDIO_DEVICE_OUT_WIRED_HEADSET, 0,
     PROFILE_LOOP_ENH_OFF, PROFILE_NAME(VC_HEADSET_LOOP_ENH_OFF)},
    {AUDIO_MODE_IN_CALL, AUDIO_DEVICE_OUT_BLUETOOTH_SCO_HEADSET, 0,
     PROFILE_LOOP_ENH_OFF, PROFILE_NAME(VC_BT_NB_LOOP_ENH_OFF)},
    {AUDIO_MODE_IN_CALL, AUDIO_DEVICE_OUT_BLUETOOTH_SCO_HEADSET, 0,
     PROFILE_LOOP_ENH_OFF, PROFILE_NAME(VC_BT_WB_LOOP_ENH_OFF)},

    {AUDIO_MODE_IN_CALL, AUDIO_DEVICE_OUT_EARPIECE, 0, PROFILE_TTY,
     PROFILE_NAME(VC_TTY)},
    {AUDIO_MODE_IN_CALL, AUDIO_DEVICE_OUT_EARPIECE, 0,
     PROFILE_TTY | PROFILE_HCO, PROFILE_NAME(VC_TTY_HCO_EARPIECE)},
    {AUDIO_MODE_IN_CALL, AUDIO_DEVICE_OUT_SPEAKER, 0, PROFILE_TTY | PROFILE_HCO,
     PROFILE_NAME(VC_TTY_HCO_SPEAKER)},
    {AUDIO_MODE_IN_CALL, AUDIO_DEVICE_OUT_EARPIECE, 0,
     PROFILE_TTY | PROFILE_VCO, PROFILE_NAME(VC_TTY_VCO_EARPIECE)},
    {AUDIO_MODE_IN_CALL, AUDIO_DEVICE_OUT_SPEAKER, 0, PROFILE_TTY | PROFILE_VCO,
     PROFILE_NAME(VC_TTY_VCO_SPEAKER)},
    {AUDIO_MODE_IN_CALL, AUDIO_DEVICE_OUT_EARPIECE, 0,
     PROFILE_TTY | PROFILE_VCO | PROFILE_DUAL_MIC,
     PROFILE_NAME(VC_TTY_VCO_EARPIECE_DUALMIC)},
    {AUDIO_MODE_IN_CALL, AUDIO_DEVICE_OUT_SPEAKER, 0,
     PROFILE_TTY | PROFILE_VCO | PROFILE_DUAL_MIC,
     PROFILE_NAME(VC_TTY_VCO_SPEAKER_DUALMIC)},

    {AUDIO_MODE_IN_CALL, AUDIO_DEVICE_OUT_EARPIECE, 0, PROFILE_LTE,
     PROFILE_NAME(VOLTE_HANDSET)},
    {AUDIO_MODE_IN_CALL, AUDIO_DEVICE_OUT_SPEAKER, 0, PROFILE_LTE,
     PROFILE_NAME(VOLTE_HANDSFREE)},
    {AUDIO_MODE_IN_CALL, AUDIO_DEVICE_OUT_WIRED_HEADSET, 0, PROFILE_LTE,
     PROFILE_NAME(VOLTE_HEADSET)},
    {AUDIO_MODE_IN_CALL, AUDIO_DEVICE_OUT_WIRED_HEADPHONE, 0, PROFILE_LTE,
     PROFILE_NAME(VOLTE_HEADPHONE)},
    {AUDIO_MODE_IN_CALL,
     AUDIO_DEVICE_OUT_SPEAKER | AUDIO_DEVICE_OUT_WIRED_HEADPHONE, 0,
     PROFILE_LTE, PROFILE_NAME(VOLTE_SPEAKERPHONE)},
    {AUDIO_MODE_IN_CALL, AUDIO_DEVICE_OUT_BLUETOOTH_SCO_HEADSET, 0, PROFILE_LTE,
     PROFILE_NAME(VOLTE_BT_NB)},
    {AUDIO_MODE_IN_CALL, AUDIO_DEVICE_OUT_BLUETOOTH_SCO_HEADSET, 0,
     PROFILE_LTE | PROFILE_BT_NREC_OFF, PROFILE_NAME(VOLTE_BT_NREC_OFF_NB)},
    {AUDIO_MODE_IN_CALL, AUDIO_DEVICE_OUT_BLUETOOTH_SCO_HEADSET, 0,
     PROFILE_LTE | PROFILE_BT_STEREO, PROFILE_NAME(VOLTE_STEREO_BT_NB)},
    {AUDIO_MODE_IN_CALL, AUDIO_DEVICE_OUT_BLUETOOTH_SCO_HEADSET, 0,
     PROFILE_LTE | PROFILE_BT_WB, PROFILE_NAME(VOLTE_BT_WB)},
    {AUDIO_MODE_IN_CALL, AUDIO_DEVICE_OUT_BLUETOOTH_SCO_HEADSET, 0,
     PROFILE_LTE | PROFILE_BT_NREC_OFF | PROFILE_BT_WB,
     PROFILE_NAME(VOLTE_BT_NREC_OFF_WB)},
    {AUDIO_MODE_IN_CALL, AUDIO_DEVICE_OUT_BLUETOOTH_SCO_HEADSET, 0,
     PROFILE_LTE | PROFILE_BT_STEREO | PROFILE_BT_WB,
     PROFILE_NAME(VOLTE_STEREO_BT_WB)},
    {AUDIO_MODE_IN_CALL, AUDIO_DEVICE_OUT_EARPIECE, 0,
     PROFILE_LTE | PROFILE_EXTRA_VOL, PROFILE_NAME(VOLTE_HANDSET_EXTRAVOL_ON)},
    {AUDIO_MODE_IN_CALL, AUDIO_DEVICE_OUT_SPEAKER, 0,
     PROFILE_LTE | PROFILE_EXTRA_VOL,
     PROFILE_NAME(VOLTE_HANDSFREE_EXTRAVOL_ON)},
    {AUDIO_MODE_IN_CALL, AUDIO_DEVICE_OUT_EARPIECE, 0,
     PROFILE_LTE | PROFILE_DUAL_MIC, PROFILE_NAME(VOLTE_HANDSET_DUALMIC)},
    {AUDIO_MODE_IN_CALL, AUDIO_DEVICE_OUT_EARPIECE, 0,
     PROFILE_LTE | PROFILE_DUAL_MIC, PROFILE_NAME(VOLTE_HEADSET_DUALMIC)},
    {AUDIO_MODE_IN_CALL, AUDIO_DEVICE_OUT_SPEAKER, 0,
     PROFILE_LTE | PROFILE_DUAL_MIC, PROFILE_NAME(VOLTE_HANDSFREE_DUALMIC)},

    {AUDIO_MODE_IN_COMMUNICATION, AUDIO_DEVICE_OUT_EARPIECE, 0, 0,
     PROFILE_NAME(VOIP_HANDSET)},
    {AUDIO_MODE_IN_COMMUNICATION, AUDIO_DEVICE_OUT_SPEAKER, 0, 0,
     PROFILE_NAME(VOIP_HANDSFREE)},
    {AUDIO_MODE_IN_COMMUNICATION, AUDIO_DEVICE_OUT_WIRED_HEADSET, 0, 0,
     PROFILE_NAME(VOIP_HEADSET)},
    {AUDIO_MODE_IN_COMMUNICATION, AUDIO_DEVICE_OUT_WIRED_HEADPHONE, 0, 0,
     PROFILE_NAME(VOIP_HEADPHONE)},
    {AUDIO_MODE_IN_COMMUNICATION,
     AUDIO_DEVICE_OUT_SPEAKER | AUDIO_DEVICE_OUT_WIRED_HEADPHONE, 0, 0,
     PROFILE_NAME(VOIP_SPEAKERPHONE)},
    {AUDIO_MODE_IN_COMMUNICATION, AUDIO_DEVICE_OUT_BLUETOOTH_SCO_HEADSET, 0, 0,
     PROFILE_NAME(VOIP_BT_NB)},
    {AUDIO_MODE_IN_COMMUNICATION, AUDIO_DEVICE_OUT_BLUETOOTH_SCO_HEADSET, 0,
     PROFILE_BT_NREC_OFF, PROFILE_NAME(VOIP_BT_NREC_OFF_NB)},
    {AUDIO_MODE_IN_COMMUNICATION, AUDIO_DEVICE_OUT_BLUETOOTH_SCO_HEADSET, 0,
     PROFILE_BT_STEREO, PROFILE_NAME(VOIP_STEREO_BT_NB)},
    {AUDIO_MODE_IN_COMMUNICATION, AUDIO_DEVICE_OUT_BLUETOOTH_SCO_HEADSET, 0,
     PROFILE_BT_WB, PROFILE_NAME(VOIP_BT_WB)},
    {AUDIO_MODE_IN_COMMUNICATION, AUDIO_DEVICE_OUT_BLUETOOTH_SCO_HEADSET, 0,
     PROFILE_BT_NREC_OFF | PROFILE_BT_WB, PROFILE_NAME(VOIP_BT_NREC_OFF_WB)},
    {AUDIO_MODE_IN_COMMUNICATION, AUDIO_DEVICE_OUT_BLUETOOTH_SCO_HEADSET, 0,
     PROFILE_BT_STEREO | PROFILE_BT_WB, PROFILE_NAME(VOIP_STEREO_BT_WB)},
    {AUDIO_MODE_IN_COMMUNICATION, AUDIO_DEVICE_OUT_EARPIECE, 0,
     PROFILE_EXTRA_VOL, PROFILE_NAME(VOIP_HANDSET_EXTRAVOL_ON)},
    {AUDIO_MODE_IN_COMMUNICATION, AUDIO_DEVICE_OUT_SPEAKER, 0,
     PROFILE_EXTRA_VOL, PROFILE_NAME(VOIP_HANDSFREE_EXTRAVOL_ON)},
    {AUDIO_MODE_IN_COMMUNICATION, AUDIO_DEVICE_OUT_EARPIECE, 0,
     PROFILE_DUAL_MIC, PROFILE_NAME(VOIP_HANDSET_DUALMIC)},
    {AUDIO_MODE_IN_COMMUNICATION, AUDIO_DEVICE_OUT_EARPIECE, 0,
     PROFILE_DUAL_MIC, PROFILE_NAME(VOIP_HEADSET_DUALMIC)},
    {AUDIO_MODE_IN_COMMUNICATION, AUDIO_DEVICE_OUT_SPEAKER, 0, PROFILE_DUAL_MIC,
     PROFILE_NAME(VOIP_HANDSFREE_DUALMIC)},
    {AUDIO_MODE_IN_COMMUNICATION, AUDIO_DEVICE_OUT_EARPIECE, 0, PROFILE_LOOP,
     PROFILE_NAME(VOIP_HANDSET_LOOP)},
    {AUDIO_MODE_IN_COMMUNICATION, AUDIO_DEVICE_OUT_SPEAKER, 0, PROFILE_LOOP,
     PROFILE_NAME(VOIP_HANDSFREE_LOOP)},
    {AUDIO_MODE_IN_COMMUNICATION, AUDIO_DEVICE_OUT_EARPIECE, 0, PROFILE_LOOP,
     PROFILE_NAME(VOIP_HEADSET_LOOP)},
    {AUDIO_MODE_IN_COMMUNICATION, AUDIO_DEVICE_OUT_BLUETOOTH_SCO_HEADSET, 0,
     PROFILE_LOOP, PROFILE_NAME(VOIP_BT_NB_LOOP)},
    {AUDIO_MODE_IN_COMMUNICATION, AUDIO_DEVICE_OUT_BLUETOOTH_SCO_HEADSET, 0,
     PROFILE_LOOP, PROFILE_NAME(VOIP_BT_WB_LOOP)},

    {AUDIO_MODE_NORMAL, AUDIO_DEVICE_OUT_SPEAKER, 0, 0,
     PROFILE_NAME(HIFI_SPEAKER)},
    {AUDIO_MODE_NORMAL, AUDIO_DEVICE_OUT_WIRED_HEADSET,
     AUDIO_DEVICE_IN_WIRED_HEADSET, 0, PROFILE_NAME(HIFI_HEADSET)},
    {AUDIO_MODE_NORMAL, AUDIO_DEVICE_OUT_SPEAKER, AUDIO_DEVICE_IN_BUILTIN_MIC,
     0, PROFILE_NAME(HIFI_MIC)},
    {AUDIO_MODE_NORMAL, AUDIO_DEVICE_OUT_EARPIECE, AUDIO_DEVICE_IN_BUILTIN_MIC,
     PROFILE_DUAL_MIC, PROFILE_NAME(HIFI_DUAL_MIC)},
};

//--------------------------------------------------------------
//-------- Helper Utilities
//--------------------------------------------------------------
#define ENUM_STR_MAP_BEGIN_PROFILE(enum_type)          \
  static const char *_getStr_profile(int enum_value) { \
    switch (enum_value) {
#define ENUM_STR_MAP_ITEM_PROFILE(e) \
  case e:                            \
    return #e;
#define ENUM_STR_MAP_END_PROFILE \
  default:                       \
    return NULL;                 \
    }                            \
    }

#define STR_ENUM_MAP_BEGIN_PROFILE(enum_type) \
  static enum_type _getEnum_profile(char *str) {
#define STR_ENUM_MAP_ITEM_PROFILE(e) \
  if (str != NULL)                   \
    if (strcmp((char *)str, #e) == 0) return e;
#define STR_ENUM_MAP_END_PROFILE       \
  return AUDIO_PROFILE_ID_ENUM_32_BIT; \
  }

#define ENUM2STR_PROFILE(enum_value) _getStr_profile(enum_value)
#define STR2ENUM_PROFILE(str) _getEnum_profile(str)

//--------------------------------------------------------------
//-------- Enum / String Map
//--------------------------------------------------------------
ENUM_STR_MAP_BEGIN_PROFILE(AUDIO_PROFILE_ID)
ENUM_STR_MAP_ITEM_PROFILE(VC_HANDSET)
ENUM_STR_MAP_ITEM_PROFILE(VC_HANDSFREE)
ENUM_STR_MAP_ITEM_PROFILE(VC_HEADSET)
ENUM_STR_MAP_ITEM_PROFILE(VC_HEADPHONE)
ENUM_STR_MAP_ITEM_PROFILE(VC_SPEAKERPHONE)
ENUM_STR_MAP_ITEM_PROFILE(VC_BT_NB)
ENUM_STR_MAP_ITEM_PROFILE(VC_BT_NREC_OFF_NB)
ENUM_STR_MAP_ITEM_PROFILE(VC_STEREO_BT_NB)
ENUM_STR_MAP_ITEM_PROFILE(VC_BT_WB)
ENUM_STR_MAP_ITEM_PROFILE(VC_BT_NREC_OFF_WB)
ENUM_STR_MAP_ITEM_PROFILE(VC_STEREO_BT_WB)
ENUM_STR_MAP_ITEM_PROFILE(VC_HANDSET_EXTRAVOL_ON)
ENUM_STR_MAP_ITEM_PROFILE(VC_HANDSFREE_EXTRAVOL_ON)
ENUM_STR_MAP_ITEM_PROFILE(VC_HANDSET_DUALMIC)
ENUM_STR_MAP_ITEM_PROFILE(VC_HEADSET_DUALMIC)
ENUM_STR_MAP_ITEM_PROFILE(VC_HANDSFREE_DUALMIC)

ENUM_STR_MAP_ITEM_PROFILE(VC_HANDSET_LOOP)
ENUM_STR_MAP_ITEM_PROFILE(VC_HANDSFREE_LOOP)
ENUM_STR_MAP_ITEM_PROFILE(VC_HEADSET_LOOP)
ENUM_STR_MAP_ITEM_PROFILE(VC_BT_NB_LOOP)
ENUM_STR_MAP_ITEM_PROFILE(VC_BT_WB_LOOP)

ENUM_STR_MAP_ITEM_PROFILE(VC_HANDSET_LOOP_ENH_OFF)
ENUM_STR_MAP_ITEM_PROFILE(VC_HANDSFREE_LOOP_ENH_OFF)
ENUM_STR_MAP_ITEM_PROFILE(VC_HEADSET_LOOP_ENH_OFF)
ENUM_STR_MAP_ITEM_PROFILE(VC_BT_NB_LOOP_ENH_OFF)
ENUM_STR_MAP_ITEM_PROFILE(VC_BT_WB_LOOP_ENH_OFF)

ENUM_STR_MAP_ITEM_PROFILE(VC_TTY)
ENUM_STR_MAP_ITEM_PROFILE(VC_TTY_HCO_EARPIECE)
ENUM_STR_MAP_ITEM_PROFILE(VC_TTY_HCO_SPEAKER)
ENUM_STR_MAP_ITEM_PROFILE(VC_TTY_VCO_EARPIECE)
ENUM_STR_MAP_ITEM_PROFILE(VC_TTY_VCO_SPEAKER)
ENUM_STR_MAP_ITEM_PROFILE(VC_TTY_VCO_EARPIECE_DUALMIC)
ENUM_STR_MAP_ITEM_PROFILE(VC_TTY_VCO_SPEAKER_DUALMIC)

ENUM_STR_MAP_ITEM_PROFILE(VOLTE_HANDSET)
ENUM_STR_MAP_ITEM_PROFILE(VOLTE_HANDSFREE)
ENUM_STR_MAP_ITEM_PROFILE(VOLTE_HEADSET)
ENUM_STR_MAP_ITEM_PROFILE(VOLTE_HEADPHONE)
ENUM_STR_MAP_ITEM_PROFILE(VOLTE_SPEAKERPHONE)
ENUM_STR_MAP_ITEM_PROFILE(VOLTE_BT_NB)
ENUM_STR_MAP_ITEM_PROFILE(VOLTE_BT_NREC_OFF_NB)
ENUM_STR_MAP_ITEM_PROFILE(VOLTE_STEREO_BT_NB)
ENUM_STR_MAP_ITEM_PROFILE(VOLTE_BT_WB)
ENUM_STR_MAP_ITEM_PROFILE(VOLTE_BT_NREC_OFF_WB)
ENUM_STR_MAP_ITEM_PROFILE(VOLTE_STEREO_BT_WB)
ENUM_STR_MAP_ITEM_PROFILE(VOLTE_HANDSET_EXTRAVOL_ON)
ENUM_STR_MAP_ITEM_PROFILE(VOLTE_HANDSFREE_EXTRAVOL_ON)
ENUM_STR_MAP_ITEM_PROFILE(VOLTE_HANDSET_DUALMIC)
ENUM_STR_MAP_ITEM_PROFILE(VOLTE_HEADSET_DUALMIC)
ENUM_STR_MAP_ITEM_PROFILE(VOLTE_HANDSFREE_DUALMIC)

ENUM_STR_MAP_ITEM_PROFILE(VOIP_HANDSET)
ENUM_STR_MAP_ITEM_PROFILE(VOIP_HANDSFREE)
ENUM_STR_MAP_ITEM_PROFILE(VOIP_HEADSET)
ENUM_STR_MAP_ITEM_PROFILE(VOIP_HEADPHONE)
ENUM_STR_MAP_ITEM_PROFILE(VOIP_SPEAKERPHONE)
ENUM_STR_MAP_ITEM_PROFILE(VOIP_BT_NB)
ENUM_STR_MAP_ITEM_PROFILE(VOIP_BT_NREC_OFF_NB)
ENUM_STR_MAP_ITEM_PROFILE(VOIP_STEREO_BT_NB)
ENUM_STR_MAP_ITEM_PROFILE(VOIP_BT_WB)
ENUM_STR_MAP_ITEM_PROFILE(VOIP_BT_NREC_OFF_WB)
ENUM_STR_MAP_ITEM_PROFILE(VOIP_STEREO_BT_WB)
ENUM_STR_MAP_ITEM_PROFILE(VOIP_HANDSET_EXTRAVOL_ON)
ENUM_STR_MAP_ITEM_PROFILE(VOIP_HANDSFREE_EXTRAVOL_ON)
ENUM_STR_MAP_ITEM_PROFILE(VOIP_HANDSET_DUALMIC)
ENUM_STR_MAP_ITEM_PROFILE(VOIP_HEADSET_DUALMIC)
ENUM_STR_MAP_ITEM_PROFILE(VOIP_HANDSFREE_DUALMIC)
ENUM_STR_MAP_ITEM_PROFILE(VOIP_HANDSET_LOOP)
ENUM_STR_MAP_ITEM_PROFILE(VOIP_HANDSFREE_LOOP)
ENUM_STR_MAP_ITEM_PROFILE(VOIP_HEADSET_LOOP)
ENUM_STR_MAP_ITEM_PROFILE(VOIP_BT_NB_LOOP)
ENUM_STR_MAP_ITEM_PROFILE(VOIP_BT_WB_LOOP)

ENUM_STR_MAP_ITEM_PROFILE(HIFI_SPEAKER)
ENUM_STR_MAP_ITEM_PROFILE(HIFI_HEADSET)
ENUM_STR_MAP_ITEM_PROFILE(HIFI_MIC)
ENUM_STR_MAP_ITEM_PROFILE(HIFI_DUAL_MIC)

ENUM_STR_MAP_ITEM_PROFILE(VT_HANDSET)
ENUM_STR_MAP_ITEM_PROFILE(VT_HANDSFREE)
ENUM_STR_MAP_ITEM_PROFILE(VT_HEADSET)
ENUM_STR_MAP_ITEM_PROFILE(VT_HEADPHONE)
ENUM_STR_MAP_ITEM_PROFILE(VT_SPEAKERPHONE)
ENUM_STR_MAP_ITEM_PROFILE(VT_BT_NB)
ENUM_STR_MAP_ITEM_PROFILE(VT_BT_NREC_OFF_NB)
ENUM_STR_MAP_ITEM_PROFILE(VT_STEREO_BT_NB)
ENUM_STR_MAP_ITEM_PROFILE(VT_BT_WB)
ENUM_STR_MAP_ITEM_PROFILE(VT_BT_NREC_OFF_WB)
ENUM_STR_MAP_ITEM_PROFILE(VT_STEREO_BT_WB)
ENUM_STR_MAP_ITEM_PROFILE(VT_HANDSET_EXTRAVOL_ON)
ENUM_STR_MAP_ITEM_PROFILE(VT_HANDSFREE_EXTRAVOL_ON)
ENUM_STR_MAP_ITEM_PROFILE(VT_HANDSET_DUALMIC)
ENUM_STR_MAP_ITEM_PROFILE(VT_HEADSET_DUALMIC)
ENUM_STR_MAP_ITEM_PROFILE(VT_HANDSFREE_DUALMIC)
ENUM_STR_MAP_ITEM_PROFILE(VT_HANDSET_LOOP)
ENUM_STR_MAP_ITEM_PROFILE(VT_HANDSFREE_LOOP)
ENUM_STR_MAP_ITEM_PROFILE(VT_HEADSET_LOOP)
ENUM_STR_MAP_ITEM_PROFILE(VT_BT_NB_LOOP)
ENUM_STR_MAP_ITEM_PROFILE(VT_BT_WB_LOOP)
ENUM_STR_MAP_END_PROFILE

STR_ENUM_MAP_BEGIN_PROFILE(AUDIO_PROFILE_ID)
STR_ENUM_MAP_ITEM_PROFILE(VC_HANDSET)
STR_ENUM_MAP_ITEM_PROFILE(VC_HANDSFREE)
STR_ENUM_MAP_ITEM_PROFILE(VC_HEADSET)
STR_ENUM_MAP_ITEM_PROFILE(VC_HEADPHONE)
STR_ENUM_MAP_ITEM_PROFILE(VC_SPEAKERPHONE)
STR_ENUM_MAP_ITEM_PROFILE(VC_BT_NB)
STR_ENUM_MAP_ITEM_PROFILE(VC_BT_NREC_OFF_NB)
STR_ENUM_MAP_ITEM_PROFILE(VC_STEREO_BT_NB)
STR_ENUM_MAP_ITEM_PROFILE(VC_BT_WB)
STR_ENUM_MAP_ITEM_PROFILE(VC_BT_NREC_OFF_WB)
STR_ENUM_MAP_ITEM_PROFILE(VC_STEREO_BT_WB)
STR_ENUM_MAP_ITEM_PROFILE(VC_HANDSET_EXTRAVOL_ON)
STR_ENUM_MAP_ITEM_PROFILE(VC_HANDSFREE_EXTRAVOL_ON)
STR_ENUM_MAP_ITEM_PROFILE(VC_HANDSET_DUALMIC)
STR_ENUM_MAP_ITEM_PROFILE(VC_HEADSET_DUALMIC)
STR_ENUM_MAP_ITEM_PROFILE(VC_HANDSFREE_DUALMIC)

STR_ENUM_MAP_ITEM_PROFILE(VC_HANDSET_LOOP)
STR_ENUM_MAP_ITEM_PROFILE(VC_HANDSFREE_LOOP)
STR_ENUM_MAP_ITEM_PROFILE(VC_HEADSET_LOOP)
STR_ENUM_MAP_ITEM_PROFILE(VC_BT_NB_LOOP)
STR_ENUM_MAP_ITEM_PROFILE(VC_BT_WB_LOOP)

STR_ENUM_MAP_ITEM_PROFILE(VC_HANDSET_LOOP_ENH_OFF)
STR_ENUM_MAP_ITEM_PROFILE(VC_HANDSFREE_LOOP_ENH_OFF)
STR_ENUM_MAP_ITEM_PROFILE(VC_HEADSET_LOOP_ENH_OFF)
STR_ENUM_MAP_ITEM_PROFILE(VC_BT_NB_LOOP_ENH_OFF)
STR_ENUM_MAP_ITEM_PROFILE(VC_BT_WB_LOOP_ENH_OFF)

STR_ENUM_MAP_ITEM_PROFILE(VC_TTY)
STR_ENUM_MAP_ITEM_PROFILE(VC_TTY_HCO_EARPIECE)
STR_ENUM_MAP_ITEM_PROFILE(VC_TTY_HCO_SPEAKER)
STR_ENUM_MAP_ITEM_PROFILE(VC_TTY_VCO_EARPIECE)
STR_ENUM_MAP_ITEM_PROFILE(VC_TTY_VCO_SPEAKER)
STR_ENUM_MAP_ITEM_PROFILE(VC_TTY_VCO_EARPIECE_DUALMIC)
STR_ENUM_MAP_ITEM_PROFILE(VC_TTY_VCO_SPEAKER_DUALMIC)

STR_ENUM_MAP_ITEM_PROFILE(VOLTE_HANDSET)
STR_ENUM_MAP_ITEM_PROFILE(VOLTE_HANDSFREE)
STR_ENUM_MAP_ITEM_PROFILE(VOLTE_HEADSET)
STR_ENUM_MAP_ITEM_PROFILE(VOLTE_HEADPHONE)
STR_ENUM_MAP_ITEM_PROFILE(VOLTE_SPEAKERPHONE)
STR_ENUM_MAP_ITEM_PROFILE(VOLTE_BT_NB)
STR_ENUM_MAP_ITEM_PROFILE(VOLTE_BT_NREC_OFF_NB)
STR_ENUM_MAP_ITEM_PROFILE(VOLTE_STEREO_BT_NB)
STR_ENUM_MAP_ITEM_PROFILE(VOLTE_BT_WB)
STR_ENUM_MAP_ITEM_PROFILE(VOLTE_BT_NREC_OFF_WB)
STR_ENUM_MAP_ITEM_PROFILE(VOLTE_STEREO_BT_WB)
STR_ENUM_MAP_ITEM_PROFILE(VOLTE_HANDSET_EXTRAVOL_ON)
STR_ENUM_MAP_ITEM_PROFILE(VOLTE_HANDSFREE_EXTRAVOL_ON)
STR_ENUM_MAP_ITEM_PROFILE(VOLTE_HANDSET_DUALMIC)
STR_ENUM_MAP_ITEM_PROFILE(VOLTE_HEADSET_DUALMIC)
STR_ENUM_MAP_ITEM_PROFILE(VOLTE_HANDSFREE_DUALMIC)

STR_ENUM_MAP_ITEM_PROFILE(VOIP_HANDSET)
STR_ENUM_MAP_ITEM_PROFILE(VOIP_HANDSFREE)
STR_ENUM_MAP_ITEM_PROFILE(VOIP_HEADSET)
STR_ENUM_MAP_ITEM_PROFILE(VOIP_HEADPHONE)
STR_ENUM_MAP_ITEM_PROFILE(VOIP_SPEAKERPHONE)
STR_ENUM_MAP_ITEM_PROFILE(VOIP_BT_NB)
STR_ENUM_MAP_ITEM_PROFILE(VOIP_BT_NREC_OFF_NB)
STR_ENUM_MAP_ITEM_PROFILE(VOIP_STEREO_BT_NB)
STR_ENUM_MAP_ITEM_PROFILE(VOIP_BT_WB)
STR_ENUM_MAP_ITEM_PROFILE(VOIP_BT_NREC_OFF_WB)
STR_ENUM_MAP_ITEM_PROFILE(VOIP_STEREO_BT_WB)
STR_ENUM_MAP_ITEM_PROFILE(VOIP_HANDSET_EXTRAVOL_ON)
STR_ENUM_MAP_ITEM_PROFILE(VOIP_HANDSFREE_EXTRAVOL_ON)
STR_ENUM_MAP_ITEM_PROFILE(VOIP_HANDSET_DUALMIC)
STR_ENUM_MAP_ITEM_PROFILE(VOIP_HEADSET_DUALMIC)
STR_ENUM_MAP_ITEM_PROFILE(VOIP_HANDSFREE_DUALMIC)
STR_ENUM_MAP_ITEM_PROFILE(VOIP_HANDSET_LOOP)
STR_ENUM_MAP_ITEM_PROFILE(VOIP_HANDSFREE_LOOP)
STR_ENUM_MAP_ITEM_PROFILE(VOIP_HEADSET_LOOP)
STR_ENUM_MAP_ITEM_PROFILE(VOIP_BT_NB_LOOP)
STR_ENUM_MAP_ITEM_PROFILE(VOIP_BT_WB_LOOP)

STR_ENUM_MAP_ITEM_PROFILE(HIFI_SPEAKER)
STR_ENUM_MAP_ITEM_PROFILE(HIFI_HEADSET)
STR_ENUM_MAP_ITEM_PROFILE(HIFI_MIC)
STR_ENUM_MAP_ITEM_PROFILE(HIFI_DUAL_MIC)

STR_ENUM_MAP_ITEM_PROFILE(VT_HANDSET)
STR_ENUM_MAP_ITEM_PROFILE(VT_HANDSFREE)
STR_ENUM_MAP_ITEM_PROFILE(VT_HEADSET)
STR_ENUM_MAP_ITEM_PROFILE(VT_HEADPHONE)
STR_ENUM_MAP_ITEM_PROFILE(VT_SPEAKERPHONE)
STR_ENUM_MAP_ITEM_PROFILE(VT_BT_NB)
STR_ENUM_MAP_ITEM_PROFILE(VT_BT_NREC_OFF_NB)
STR_ENUM_MAP_ITEM_PROFILE(VT_STEREO_BT_NB)
STR_ENUM_MAP_ITEM_PROFILE(VT_BT_WB)
STR_ENUM_MAP_ITEM_PROFILE(VT_BT_NREC_OFF_WB)
STR_ENUM_MAP_ITEM_PROFILE(VT_STEREO_BT_WB)
STR_ENUM_MAP_ITEM_PROFILE(VT_HANDSET_EXTRAVOL_ON)
STR_ENUM_MAP_ITEM_PROFILE(VT_HANDSFREE_EXTRAVOL_ON)
STR_ENUM_MAP_ITEM_PROFILE(VT_HANDSET_DUALMIC)
STR_ENUM_MAP_ITEM_PROFILE(VT_HEADSET_DUALMIC)
STR_ENUM_MAP_ITEM_PROFILE(VT_HANDSFREE_DUALMIC)
STR_ENUM_MAP_ITEM_PROFILE(VT_HANDSET_LOOP)
STR_ENUM_MAP_ITEM_PROFILE(VT_HANDSFREE_LOOP)
STR_ENUM_MAP_ITEM_PROFILE(VT_HEADSET_LOOP)
STR_ENUM_MAP_ITEM_PROFILE(VT_BT_NB_LOOP)
STR_ENUM_MAP_ITEM_PROFILE(VT_BT_WB_LOOP)
STR_ENUM_MAP_END_PROFILE

#endif /* __AUDIO_PROFILE_H__ */
