#******************************************************************************
# (C) Copyright [2010 - 2011] Marvell International Ltd.
# All Rights Reserved
#******************************************************************************


# this file is for board dependent configurations

#**********************************************************************
# * Explanation of each macro
# *
# *  1. BUILD_OPTION_STRATEGY_ENABLE_RESIZER
# *  NOTE: enable IPP software primitives/GCU to do resize
# *
# *  2. BUILD_OPTION_STRATEGY_ENABLE_ROTATOR
# *  NOTE:enable IPP software primitives/GCU to do rotate
# *
# *  3. BUILD_OPTION_STRATEGY_ENABLE_CSC_CBYCRY_RGB
# *  NOTE: do color space conversion from UYVY to RGB
# *
# *  4. BUILD_OPTION_STRATEGY_ENABLE_CSC_YCC420P_YCC420SP
# *  NOTE: do color space conversion from YUV420p to YUV420sp
# *
# *  5. BUILD_OPTION_STRATEGY_ENABLE_IPPJPEGENCODER
# *  NOTE: enable ipp software JPEG encoder for low-end sensor
# *
# *  // following are camera specialized features
# *
# *  6. BUILD_OPTION_STRATEGY_ENABLE_SNAPSHOT
# *  NOTE: generate a snapshot in preview port while still state
# *
# *  7. BUILD_OPTION_STRATEGY_MAX_DIGITALZOOM_Q16  ( <value> << 16 )
# *  NOTE: max digital zoom supported, since digital zoom is done by the
# *        co-work of sensor and camera engine post processing unit, pls
# *        make a balance here between feature and performance. An advice
# *        is that during preview we need always need sensor to do zoom
# *        for fps performance, so just not set a value out of sensor's
# *        capability of your target preview size.
# *
# *  8. BUILD_OPTION_STRATEGY_ENABLE_AUTOFOCUS
# *  NOTE: Just used in Marvell tuned sensor, since many platform may use
# *        a same sensor, but have different driver status, we need open
# *        this path in ready platform, and close it at verse
# *
# *  9. BUILD_OPTION_STRATEGY_ENABLE_FLASH
# *  NOTE: enable flash if flash is installed & flash control
# *        is implemented in your platform
# *
# * 10. BUILD_OPTION_STRATEGY_DISABLE_DYNAMIC_SENSOR_DETECT
# *  NOTE: disable sensor dynamically detect mechanism to save camera off to viewfinder on latency
# *
# * 11. BUILD_OPTION_STRATEGY_MAX_ZSL_DEPTH
# *  NOTE: max zsl depth camera engine supported, if this value
# *        is set 0, it means that ppu ZSL functionality has been disabled.
# *        When ZSL enabled, ShutterLag = -( ZslDepth - 1 ), and a negative
# *        ShutterLag means an earlier frame will be captured.
# *
# * 12. BUILD_OPTION_STRATEGY_ENABLE_FACEDETECTION
# *  NOTE: enalbe face detection
# *
# *  // following are V4L2 workaround
# * 13. BUILD_OPTION_WORKAROUND_V4L2_FRAMERATECONTROL_BY_DROPFRAME
# *
# * 14. BUILD_OPTION_WORKAROUND_V4L2_STREAMON_AFTER_ALLENQUEUE
# *
# * 15. BUILD_OPTION_WORKAROUND_V4L2_SAVE_RESTORE_WB
# *  NOTE: used to do white balance save/restore in engine, incase sensor white balance
# *        is destroyed by driver, which lead capture image to be green.
# *
# * 16. BUILD_OPTION_WORKAROUND_V4L2_FLUSH_BY_REOPEN
# *
# *  // followings are only for debug
# * 17. BUILD_OPTION_DEBUG_DUMP_V4L2_CALLING
# *  NOTE: dump V4L2 driver calling sequence and result to check
# *
# * 18. BUILD_OPTION_DEBUG_DUMP_CE_CALLING
# *  NOTE: dump camera-engine calling sequence and result to check
# *
# * 19. BUILD_OPTION_DEBUG_DUMP_CE_FILE       "ce_callseq_dump.txt"
# *  NOTE: the file to which camera-engine calling sequence dumped
# *
# * 20. BUILD_OPTION_DEBUG_DISABLE_SAVE_RESTORE_3A
# *
# * 21. BUILD_OPTION_DEBUG_DISABLE_PROCESS_THREAD
# *
# * 22. BUILD_OPTION_DEBUG_ENABLE_FAKE_SENSOR
# *
# * 23. BUILD_OPTION_DEBUG_PROFILE_PERFORMANCE
# *  NOTE: dump profile time data to check engine and sensor performance
#**************************************************************************

# mg/nevo family
ifeq ($(TARGET_PRODUCT), saarbmg1)
LOCAL_CFLAGS    += -D PLATFORM_BOARD_MG1SAARB \
                   -D PLATFORM_PROCESSOR_MG1 \
                   -D PLATFORM_CCIC_SENSOR_MCLK=26

# ppu unit turn on/off
#LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_RESIZER
#LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_ROTATOR
#LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_CSC_CBYCRY_RGB
LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_CSC_YCC420P_YCC420SP
LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_IPPJPEGENCODER

# features
LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_SNAPSHOT
LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_MAX_DIGITALZOOM_Q16=2*65536
#LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_AUTOFOCUS
LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_FLASH
LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_MAX_ZSL_DEPTH=0
#LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_DISABLE_DYNAMIC_SENSOR_DETECT
#LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_FACEDETECTION

#  V4L2 workaround
LOCAL_CFLAGS += -D BUILD_OPTION_WORKAROUND_V4L2_FRAMERATECONTROL_BY_DROPFRAME
LOCAL_CFLAGS += -D BUILD_OPTION_WORKAROUND_V4L2_STREAMON_AFTER_ALLENQUEUE
#LOCAL_CFLAGS += -D BUILD_OPTION_WORKAROUND_V4L2_SAVE_RESTORE_WB
#LOCAL_CFLAGS += -D BUILD_OPTION_WORKAROUND_V4L2_FLUSH_BY_REOPEN

# for debug
#LOCAL_CFLAGS += -D BUILD_OPTION_DEBUG_DUMP_V4L2_CALLING
#LOCAL_CFLAGS += -D BUILD_OPTION_DEBUG_DUMP_CE_CALLING
#LOCAL_CFLAGS += -D BUILD_OPTION_DEBUG_DUMP_CE_FILE="ce_callseq_dump.txt"
#LOCAL_CFLAGS += -D BUILD_OPTION_DEBUG_PROFILE_PERFORMANCE

#LOCAL_CFLAGS += -D BUILD_OPTION_DEBUG_DISABLE_SAVE_RESTORE_3A
#LOCAL_CFLAGS += -D BUILD_OPTION_DEBUG_DISABLE_PROCESS_THREAD
#LOCAL_CFLAGS += -D BUILD_OPTION_DEBUG_ENABLE_FAKE_SENSOR

ENABLE_EXT_ISP = y
ENABLE_DXO_ISP = n
MACH_ARCH := pxa
endif

ifeq ($(TARGET_PRODUCT), evbmg1)
LOCAL_CFLAGS += -D PLATFORM_BOARD_MG1EVB \
                -D PLATFORM_PROCESSOR_MG1 \
                -D PLATFORM_CCIC_SENSOR_MCLK=26

# ppu unit turn on/off
#LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_RESIZER
#LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_ROTATOR
#LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_CSC_CBYCRY_RGB
LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_CSC_YCC420P_YCC420SP
LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_IPPJPEGENCODER

# features
LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_SNAPSHOT
LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_MAX_DIGITALZOOM_Q16=2*65536
#LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_AUTOFOCUS
LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_FLASH
LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_MAX_ZSL_DEPTH=0
#LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_DISABLE_DYNAMIC_SENSOR_DETECT
#LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_FACEDETECTION

#  V4L2 workaround
LOCAL_CFLAGS += -D BUILD_OPTION_WORKAROUND_V4L2_FRAMERATECONTROL_BY_DROPFRAME
LOCAL_CFLAGS += -D BUILD_OPTION_WORKAROUND_V4L2_STREAMON_AFTER_ALLENQUEUE
#LOCAL_CFLAGS += -D BUILD_OPTION_WORKAROUND_V4L2_SAVE_RESTORE_WB
#LOCAL_CFLAGS += -D BUILD_OPTION_WORKAROUND_V4L2_FLUSH_BY_REOPEN

# for debug
#LOCAL_CFLAGS += -D BUILD_OPTION_DEBUG_DUMP_V4L2_CALLING
#LOCAL_CFLAGS += -D BUILD_OPTION_DEBUG_DUMP_CE_CALLING
#LOCAL_CFLAGS += -D BUILD_OPTION_DEBUG_DUMP_CE_FILE="ce_callseq_dump.txt"
#LOCAL_CFLAGS += -D BUILD_OPTION_DEBUG_PROFILE_PERFORMANCE

#LOCAL_CFLAGS += -D BUILD_OPTION_DEBUG_DISABLE_SAVE_RESTORE_3A
#LOCAL_CFLAGS += -D BUILD_OPTION_DEBUG_DISABLE_PROCESS_THREAD
#LOCAL_CFLAGS += -D BUILD_OPTION_DEBUG_ENABLE_FAKE_SENSOR

ENABLE_EXT_ISP = y
ENABLE_DXO_ISP = n
MACH_ARCH := pxa
endif

ifeq ($(TARGET_PRODUCT), nevo)
LOCAL_CFLAGS    += -D PLATFORM_BOARD_NEVO \
                   -D PLATFORM_PROCESSOR_NEVO \
                   -D PLATFORM_CCIC_SENSOR_MCLK=26

# ppu unit turn on/off
#LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_RESIZER
#LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_ROTATOR
#LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_CSC_CBYCRY_RGB
#LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_CSC_YCC420P_YCC420SP
LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_IPPJPEGENCODER

# features
#LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_SNAPSHOT
LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_MAX_DIGITALZOOM_Q16=2*65536
#LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_AUTOFOCUS
LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_FLASH
LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_MAX_ZSL_DEPTH=0
#LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_DISABLE_DYNAMIC_SENSOR_DETECT
#LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_FACEDETECTION

#  V4L2 workaround
LOCAL_CFLAGS += -D BUILD_OPTION_WORKAROUND_V4L2_FRAMERATECONTROL_BY_DROPFRAME
LOCAL_CFLAGS += -D BUILD_OPTION_WORKAROUND_V4L2_STREAMON_AFTER_ALLENQUEUE
#LOCAL_CFLAGS += -D BUILD_OPTION_WORKAROUND_V4L2_SAVE_RESTORE_WB
#LOCAL_CFLAGS += -D BUILD_OPTION_WORKAROUND_V4L2_FLUSH_BY_REOPEN

# for debug
#LOCAL_CFLAGS += -D BUILD_OPTION_DEBUG_DUMP_V4L2_CALLING
#LOCAL_CFLAGS += -D BUILD_OPTION_DEBUG_DUMP_CE_CALLING
#LOCAL_CFLAGS += -D BUILD_OPTION_DEBUG_DUMP_CE_FILE="ce_callseq_dump.txt"
#LOCAL_CFLAGS += -D BUILD_OPTION_DEBUG_PROFILE_PERFORMANCE

#LOCAL_CFLAGS += -D BUILD_OPTION_DEBUG_DISABLE_SAVE_RESTORE_3A
#LOCAL_CFLAGS += -D BUILD_OPTION_DEBUG_DISABLE_PROCESS_THREAD
#LOCAL_CFLAGS += -D BUILD_OPTION_DEBUG_ENABLE_FAKE_SENSOR

ENABLE_EXT_ISP = y
ENABLE_DXO_ISP = n
MACH_ARCH := pxa
endif

ifeq ($(TARGET_PRODUCT), evbnevo)
LOCAL_CFLAGS    += -D PLATFORM_BOARD_NEVOEVB \
                   -D PLATFORM_PROCESSOR_NEVO \
                   -D PLATFORM_CCIC_SENSOR_MCLK=26

# ppu unit turn on/off
#LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_RESIZER
#LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_ROTATOR
#LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_CSC_CBYCRY_RGB
#LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_CSC_YCC420P_YCC420SP
LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_IPPJPEGENCODER

# features
#LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_SNAPSHOT
LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_MAX_DIGITALZOOM_Q16=2*65536
#LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_AUTOFOCUS
LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_FLASH
LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_MAX_ZSL_DEPTH=0
#LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_DISABLE_DYNAMIC_SENSOR_DETECT
#LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_FACEDETECTION

#  V4L2 workaround
LOCAL_CFLAGS += -D BUILD_OPTION_WORKAROUND_V4L2_FRAMERATECONTROL_BY_DROPFRAME
LOCAL_CFLAGS += -D BUILD_OPTION_WORKAROUND_V4L2_STREAMON_AFTER_ALLENQUEUE
#LOCAL_CFLAGS += -D BUILD_OPTION_WORKAROUND_V4L2_SAVE_RESTORE_WB
#LOCAL_CFLAGS += -D BUILD_OPTION_WORKAROUND_V4L2_FLUSH_BY_REOPEN

# for debug
#LOCAL_CFLAGS += -D BUILD_OPTION_DEBUG_DUMP_V4L2_CALLING
#LOCAL_CFLAGS += -D BUILD_OPTION_DEBUG_DUMP_CE_CALLING
#LOCAL_CFLAGS += -D BUILD_OPTION_DEBUG_DUMP_CE_FILE="ce_callseq_dump.txt"
#LOCAL_CFLAGS += -D BUILD_OPTION_DEBUG_PROFILE_PERFORMANCE

#LOCAL_CFLAGS += -D BUILD_OPTION_DEBUG_DISABLE_SAVE_RESTORE_3A
#LOCAL_CFLAGS += -D BUILD_OPTION_DEBUG_DISABLE_PROCESS_THREAD
#LOCAL_CFLAGS += -D BUILD_OPTION_DEBUG_ENABLE_FAKE_SENSOR

ENABLE_EXT_ISP = y
ENABLE_DXO_ISP = n
MACH_ARCH := pxa
endif

# mmp family
ifeq ($(TARGET_PRODUCT), brownstone)
LOCAL_CFLAGS    += -D PLATFORM_BOARD_BROWNSTONE \
                   -D PLATFORM_PROCESSOR_MMP2 \
                   -D PLATFORM_CCIC_SENSOR_MCLK=25

# ppu unit turn on/off
#LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_RESIZER
#LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_ROTATOR
#LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_CSC_CBYCRY_RGB
LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_CSC_YCC420P_YCC420SP
LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_IPPJPEGENCODER
#LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_VMETAJPEGENCODER

# features
#LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_SNAPSHOT
LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_MAX_DIGITALZOOM_Q16=1*65536
#LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_AUTOFOCUS
#LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_FLASH
LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_MAX_ZSL_DEPTH=0
#LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_DISABLE_DYNAMIC_SENSOR_DETECT
#LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_FACEDETECTION

#  V4L2 workaround
LOCAL_CFLAGS += -D BUILD_OPTION_WORKAROUND_V4L2_FRAMERATECONTROL_BY_DROPFRAME
LOCAL_CFLAGS += -D BUILD_OPTION_WORKAROUND_V4L2_STREAMON_AFTER_ALLENQUEUE
LOCAL_CFLAGS += -D BUILD_OPTION_WORKAROUND_V4L2_SAVE_RESTORE_WB
#LOCAL_CFLAGS += -D BUILD_OPTION_WORKAROUND_V4L2_FLUSH_BY_REOPEN

# for debug
#LOCAL_CFLAGS += -D BUILD_OPTION_DEBUG_DUMP_V4L2_CALLING
#LOCAL_CFLAGS += -D BUILD_OPTION_DEBUG_DUMP_CE_CALLING
#LOCAL_CFLAGS += -D BUILD_OPTION_DEBUG_DUMP_CE_FILE="ce_callseq_dump.txt"
#LOCAL_CFLAGS += -D BUILD_OPTION_DEBUG_PROFILE_PERFORMANCE

#LOCAL_CFLAGS += -D BUILD_OPTION_DEBUG_DISABLE_SAVE_RESTORE_3A
#LOCAL_CFLAGS += -D BUILD_OPTION_DEBUG_DISABLE_PROCESS_THREAD
#LOCAL_CFLAGS += -D BUILD_OPTION_DEBUG_ENABLE_FAKE_SENSOR

ENABLE_EXT_ISP = y
ENABLE_DXO_ISP = n

DXO_FIRMWARE_VERSION = lqu0001

MACH_ARCH := mmp
endif

ifeq ($(TARGET_PRODUCT), g50)
LOCAL_CFLAGS    += -D PLATFORM_BOARD_G50 \
                   -D PLATFORM_PROCESSOR_MMP2 \
                   -D PLATFORM_CCIC_SENSOR_MCLK=25

# ppu unit turn on/off
#LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_RESIZER
#LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_ROTATOR
#LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_CSC_CBYCRY_RGB
LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_CSC_YCC420P_YCC420SP
LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_IPPJPEGENCODER

# features
#LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_SNAPSHOT
LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_MAX_DIGITALZOOM_Q16=1*65536
#LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_AUTOFOCUS
#LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_FLASH
LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_MAX_ZSL_DEPTH=0
#LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_DISABLE_DYNAMIC_SENSOR_DETECT
#LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_FACEDETECTION

#  V4L2 workaround
LOCAL_CFLAGS += -D BUILD_OPTION_WORKAROUND_V4L2_FRAMERATECONTROL_BY_DROPFRAME
LOCAL_CFLAGS += -D BUILD_OPTION_WORKAROUND_V4L2_STREAMON_AFTER_ALLENQUEUE
#LOCAL_CFLAGS += -D BUILD_OPTION_WORKAROUND_V4L2_SAVE_RESTORE_WB
#LOCAL_CFLAGS += -D BUILD_OPTION_WORKAROUND_V4L2_FLUSH_BY_REOPEN

# for debug
#LOCAL_CFLAGS += -D BUILD_OPTION_DEBUG_DUMP_V4L2_CALLING
#LOCAL_CFLAGS += -D BUILD_OPTION_DEBUG_DUMP_CE_CALLING
#LOCAL_CFLAGS += -D BUILD_OPTION_DEBUG_DUMP_CE_FILE="ce_callseq_dump.txt"
#LOCAL_CFLAGS += -D BUILD_OPTION_DEBUG_PROFILE_PERFORMANCE

#LOCAL_CFLAGS += -D BUILD_OPTION_DEBUG_DISABLE_SAVE_RESTORE_3A
#LOCAL_CFLAGS += -D BUILD_OPTION_DEBUG_DISABLE_PROCESS_THREAD
#LOCAL_CFLAGS += -D BUILD_OPTION_DEBUG_ENABLE_FAKE_SENSOR

ENABLE_EXT_ISP = y
ENABLE_DXO_ISP = n

MACH_ARCH := mmp
endif

ifeq ($(TARGET_PRODUCT), abilene)
LOCAL_CFLAGS    += -D PLATFORM_BOARD_ABILENE \
                   -D PLATFORM_PROCESSOR_MMP3 \
                   -D PLATFORM_CCIC_SENSOR_MCLK=25

ENABLE_MC_DRV = y
ENABLE_VMETA  = y
ENABLE_ISP_AUTO_RESET = n
# ppu unit turn on/off
#LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_RESIZER
#LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_ROTATOR
#LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_CSC_CBYCRY_RGB
LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_CSC_YCC420P_YCC420SP
LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_IPPJPEGENCODER

ifeq ($(ENABLE_VMETA), y)
LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_VMETAJPEGENCODER
endif

ifeq ($(ENABLE_MC_DRV), y)
LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_MC
endif

ifeq ($(ENABLE_ISP_AUTO_RESET), y)
LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_ISP_AUTO_RESET
endif

# features
#LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_SNAPSHOT
LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_MAX_DIGITALZOOM_Q16=5*65536
#LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_AUTOFOCUS
#LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_FLASH
LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_MAX_ZSL_DEPTH=0
#LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_DISABLE_DYNAMIC_SENSOR_DETECT
#LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_FACEDETECTION

#  V4L2 workaround
LOCAL_CFLAGS += -D BUILD_OPTION_WORKAROUND_V4L2_FRAMERATECONTROL_BY_DROPFRAME
LOCAL_CFLAGS += -D BUILD_OPTION_WORKAROUND_V4L2_STREAMON_AFTER_ALLENQUEUE
LOCAL_CFLAGS += -D BUILD_OPTION_WORKAROUND_V4L2_SAVE_RESTORE_WB
#LOCAL_CFLAGS += -D BUILD_OPTION_WORKAROUND_V4L2_FLUSH_BY_REOPEN

# for debug
#LOCAL_CFLAGS += -D BUILD_OPTION_DEBUG_DUMP_V4L2_CALLING
#LOCAL_CFLAGS += -D BUILD_OPTION_DEBUG_DUMP_CE_CALLING
#LOCAL_CFLAGS += -D BUILD_OPTION_DEBUG_DUMP_CE_FILE="ce_callseq_dump.txt"
#LOCAL_CFLAGS += -D BUILD_OPTION_DEBUG_DUMP_ISP_EVENT_LATENCY
#LOCAL_CFLAGS += -D BUILD_OPTION_DEBUG_PROFILE_PERFORMANCE

#LOCAL_CFLAGS += -D BUILD_OPTION_DEBUG_DISABLE_SAVE_RESTORE_3A
#LOCAL_CFLAGS += -D BUILD_OPTION_DEBUG_DISABLE_PROCESS_THREAD
#LOCAL_CFLAGS += -D BUILD_OPTION_DEBUG_ENABLE_FAKE_SENSOR

ENABLE_EXT_ISP = y
ENABLE_DXO_ISP = y

DXO_FIRMWARE_VERSION = lqu0011

MACH_ARCH := mmp
endif

ifeq ($(TARGET_PRODUCT), orchid)
LOCAL_CFLAGS    += -D PLATFORM_BOARD_ORCHID \
                   -D PLATFORM_PROCESSOR_MMP3 \
                   -D PLATFORM_CCIC_SENSOR_MCLK=25

ENABLE_MC_DRV = y
ENABLE_VMETA  = y
ENABLE_ISP_AUTO_RESET = n
# ppu unit turn on/off
#LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_RESIZER
#LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_ROTATOR
#LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_CSC_CBYCRY_RGB
LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_CSC_YCC420P_YCC420SP
LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_IPPJPEGENCODER

ifeq ($(ENABLE_VMETA), y)
LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_VMETAJPEGENCODER
endif

ifeq ($(ENABLE_MC_DRV), y)
LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_MC
endif

ifeq ($(ENABLE_ISP_AUTO_RESET), y)
LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_ISP_AUTO_RESET
endif

# features
#LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_SNAPSHOT
LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_MAX_DIGITALZOOM_Q16=3*65536
#LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_AUTOFOCUS
#LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_FLASH
LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_MAX_ZSL_DEPTH=0
#LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_DISABLE_DYNAMIC_SENSOR_DETECT
#LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_FACEDETECTION

#  V4L2 workaround
LOCAL_CFLAGS += -D BUILD_OPTION_WORKAROUND_V4L2_FRAMERATECONTROL_BY_DROPFRAME
LOCAL_CFLAGS += -D BUILD_OPTION_WORKAROUND_V4L2_STREAMON_AFTER_ALLENQUEUE
LOCAL_CFLAGS += -D BUILD_OPTION_WORKAROUND_V4L2_SAVE_RESTORE_WB
#LOCAL_CFLAGS += -D BUILD_OPTION_WORKAROUND_V4L2_FLUSH_BY_REOPEN

# for debug
#LOCAL_CFLAGS += -D BUILD_OPTION_DEBUG_DUMP_V4L2_CALLING
#LOCAL_CFLAGS += -D BUILD_OPTION_DEBUG_DUMP_CE_CALLING
#LOCAL_CFLAGS += -D BUILD_OPTION_DEBUG_DUMP_CE_FILE="ce_callseq_dump.txt"
#LOCAL_CFLAGS += -D BUILD_OPTION_DEBUG_DUMP_ISP_EVENT_LATENCY
#LOCAL_CFLAGS += -D BUILD_OPTION_DEBUG_DUMP_ISP_SHOOTING_PARAMETERS
#LOCAL_CFLAGS += -D BUILD_OPTION_DEBUG_PROFILE_PERFORMANCE

#LOCAL_CFLAGS += -D BUILD_OPTION_DEBUG_DISABLE_SAVE_RESTORE_3A
#LOCAL_CFLAGS += -D BUILD_OPTION_DEBUG_DISABLE_PROCESS_THREAD
#LOCAL_CFLAGS += -D BUILD_OPTION_DEBUG_ENABLE_FAKE_SENSOR

ENABLE_EXT_ISP = y
ENABLE_DXO_ISP = y

DXO_FIRMWARE_VERSION = lqu0011

MACH_ARCH := mmp
endif

LOCAL_CFLAGS    += -D PLATFORM_BOARD_MK2 \
                   -D PLATFORM_PROCESSOR_MMP3 \
                   -D PLATFORM_CCIC_SENSOR_MCLK=25

ENABLE_VMETA  = y
# ppu unit turn on/off
#LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_RESIZER
#LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_ROTATOR
#LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_CSC_CBYCRY_RGB
LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_CSC_YCC420P_YCC420SP
LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_IPPJPEGENCODER
LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_VMETAJPEGENCODER


# features
#LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_SNAPSHOT
LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_MAX_DIGITALZOOM_Q16=3*65536
LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_AUTOFOCUS
#LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_FLASH
LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_MAX_ZSL_DEPTH=0
#LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_DISABLE_DYNAMIC_SENSOR_DETECT
#LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_FACEDETECTION

#  V4L2 workaround
LOCAL_CFLAGS += -D BUILD_OPTION_WORKAROUND_V4L2_FRAMERATECONTROL_BY_DROPFRAME
LOCAL_CFLAGS += -D BUILD_OPTION_WORKAROUND_V4L2_STREAMON_AFTER_ALLENQUEUE
LOCAL_CFLAGS += -D BUILD_OPTION_WORKAROUND_V4L2_SAVE_RESTORE_WB
LOCAL_CFLAGS += -D BUILD_OPTION_WORKAROUND_V4L2_RESET_FOCUS_AFTER_STREAMON
#LOCAL_CFLAGS += -D BUILD_OPTION_WORKAROUND_V4L2_FLUSH_BY_REOPEN

# for debug
#LOCAL_CFLAGS += -D BUILD_OPTION_DEBUG_DUMP_V4L2_CALLING
#LOCAL_CFLAGS += -D BUILD_OPTION_DEBUG_DUMP_CE_CALLING
#LOCAL_CFLAGS += -D BUILD_OPTION_DEBUG_DUMP_CE_FILE="ce_callseq_dump.txt"
#LOCAL_CFLAGS += -D BUILD_OPTION_DEBUG_DUMP_ISP_EVENT_LATENCY
#LOCAL_CFLAGS += -D BUILD_OPTION_DEBUG_DUMP_ISP_SHOOTING_PARAMETERS
#LOCAL_CFLAGS += -D BUILD_OPTION_DEBUG_PROFILE_PERFORMANCE

#LOCAL_CFLAGS += -D BUILD_OPTION_DEBUG_DISABLE_SAVE_RESTORE_3A
#LOCAL_CFLAGS += -D BUILD_OPTION_DEBUG_DISABLE_PROCESS_THREAD
#LOCAL_CFLAGS += -D BUILD_OPTION_DEBUG_ENABLE_FAKE_SENSOR

ENABLE_EXT_ISP = y
ENABLE_DXO_ISP = n

MACH_ARCH := mmp

ifeq ($(TARGET_PRODUCT), yellowstone)
LOCAL_CFLAGS    += -D PLATFORM_BOARD_YELLOWSTONE \
                   -D PLATFORM_PROCESSOR_MMP3 \
                   -D PLATFORM_CCIC_SENSOR_MCLK=25

ENABLE_MC_DRV = n
# ppu unit turn on/off
#LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_RESIZER
#LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_ROTATOR
#LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_CSC_CBYCRY_RGB
LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_CSC_YCC420P_YCC420SP
LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_IPPJPEGENCODER

ifeq ($(ENABLE_MC_DRV), y)
CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_MC
endif

# features
#LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_SNAPSHOT
LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_MAX_DIGITALZOOM_Q16=5*65536
#LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_AUTOFOCUS
#LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_FLASH
LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_MAX_ZSL_DEPTH=0
#LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_DISABLE_DYNAMIC_SENSOR_DETECT
#LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_FACEDETECTION

#  V4L2 workaround
LOCAL_CFLAGS += -D BUILD_OPTION_WORKAROUND_V4L2_FRAMERATECONTROL_BY_DROPFRAME
LOCAL_CFLAGS += -D BUILD_OPTION_WORKAROUND_V4L2_STREAMON_AFTER_ALLENQUEUE
LOCAL_CFLAGS += -D BUILD_OPTION_WORKAROUND_V4L2_SAVE_RESTORE_WB
#LOCAL_CFLAGS += -D BUILD_OPTION_WORKAROUND_V4L2_FLUSH_BY_REOPEN

# for debug
#LOCAL_CFLAGS += -D BUILD_OPTION_DEBUG_DUMP_MC_TIMING
#LOCAL_CFLAGS += -D BUILD_OPTION_DEBUG_DUMP_MC_CALLING
#LOCAL_CFLAGS += -D BUILD_OPTION_DEBUG_DUMP_V4L2_CALLING
#LOCAL_CFLAGS += -D BUILD_OPTION_DEBUG_DUMP_CE_CALLING
#LOCAL_CFLAGS += -D BUILD_OPTION_DEBUG_DUMP_CE_FILE="ce_callseq_dump.txt"
#LOCAL_CFLAGS += -D BUILD_OPTION_DEBUG_DUMP_ISP_EVENT_LATENCY
#LOCAL_CFLAGS += -D BUILD_OPTION_DEBUG_PROFILE_PERFORMANCE

#LOCAL_CFLAGS += -D BUILD_OPTION_DEBUG_DISABLE_SAVE_RESTORE_3A
#LOCAL_CFLAGS += -D BUILD_OPTION_DEBUG_DISABLE_PROCESS_THREAD
#LOCAL_CFLAGS += -D BUILD_OPTION_DEBUG_ENABLE_FAKE_SENSOR

ENABLE_EXT_ISP = y
ENABLE_DXO_ISP = n

DXO_FIRMWARE_VERSION = lqu0011

MACH_ARCH := mmp
endif

# tavor td/ttc family
ifeq ($(TARGET_PRODUCT), dkb)
LOCAL_CFLAGS    += -D PLATFORM_BOARD_TDDKB \
                   -D PLATFORM_PROCESSOR_TD \
                   -D PLATFORM_CCIC_SENSOR_MCLK=24

# ppu unit turn on/off
#LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_RESIZER
#LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_ROTATOR
#LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_CSC_CBYCRY_RGB
LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_CSC_YCC420P_YCC420SP
LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_IPPJPEGENCODER

# features
LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_SNAPSHOT
LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_MAX_DIGITALZOOM_Q16=3*65536
LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_AUTOFOCUS
#LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_FLASH
LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_MAX_ZSL_DEPTH=2
#LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_DISABLE_DYNAMIC_SENSOR_DETECT
LOCAL_CFLAGS += -D BUILD_OPTION_STRATEGY_ENABLE_FACEDETECTION

#  V4L2 workaround
LOCAL_CFLAGS += -D BUILD_OPTION_WORKAROUND_V4L2_FRAMERATECONTROL_BY_DROPFRAME
LOCAL_CFLAGS += -D BUILD_OPTION_WORKAROUND_V4L2_STREAMON_AFTER_ALLENQUEUE
#LOCAL_CFLAGS += -D BUILD_OPTION_WORKAROUND_V4L2_SAVE_RESTORE_WB
#LOCAL_CFLAGS += -D BUILD_OPTION_WORKAROUND_V4L2_FLUSH_BY_REOPEN

# for debug
#LOCAL_CFLAGS += -D BUILD_OPTION_DEBUG_DUMP_V4L2_CALLING
#LOCAL_CFLAGS += -D BUILD_OPTION_DEBUG_DUMP_CE_CALLING
#LOCAL_CFLAGS += -D BUILD_OPTION_DEBUG_DUMP_CE_FILE="ce_callseq_dump.txt"
#LOCAL_CFLAGS += -D BUILD_OPTION_DEBUG_PROFILE_PERFORMANCE

#LOCAL_CFLAGS += -D BUILD_OPTION_DEBUG_DISABLE_SAVE_RESTORE_3A
#LOCAL_CFLAGS += -D BUILD_OPTION_DEBUG_DISABLE_PROCESS_THREAD
#LOCAL_CFLAGS += -D BUILD_OPTION_DEBUG_ENABLE_FAKE_SENSOR

ENABLE_EXT_ISP = y
ENABLE_DXO_ISP = n

MACH_ARCH := mmp
endif

ifeq (${ENABLE_EXT_ISP}, y)
LOCAL_CFLAGS += -D EXT
endif

ifeq (${ENABLE_DXO_ISP}, y)
LOCAL_CFLAGS += -D DXO
endif

#LOCAL_CFLAGS += -Wall
